#!/bin/sh
# =============================================================================
# events.sh — Network Event Detection for QManager
# =============================================================================
# Sourced by qmanager_poller. Detects changes in network state and appends
# events to the NDJSON events file for the Recent Activities component.
#
# Dependencies: qlog_* functions, global state variables from poller
# Install location: /usr/lib/qmanager/events.sh
#
# Global variables used (defined in poller):
#   Read:  network_type, lte_band, lte_pci, nr_band, nr_pci, nr_state,
#          modem_reachable, conn_internet_available, t2_ca_active, t2_ca_count,
#          t2_nr_ca_active, t2_nr_ca_count, service_status
#   Write: prev_ev_*, events_initialized
# =============================================================================

# Append a single event to the events file (NDJSON — one JSON per line)
# Note: All message content is generated by us (band names, PCI numbers, etc.)
# so no user-input escaping is needed.
append_event() {
    local etype="$1" message="$2" severity="${3:-info}"
    local ts
    ts=$(date +%s)

    jq -n -c \
        --argjson ts "$ts" \
        --arg type "$etype" \
        --arg message "$message" \
        --arg severity "$severity" \
        '{timestamp: $ts, type: $type, message: $message, severity: $severity}' >> "$EVENTS_FILE"

    # Trim to max entries
    local count
    count=$(wc -l < "$EVENTS_FILE" 2>/dev/null || echo 0)
    if [ "$count" -gt "$MAX_EVENTS" ]; then
        local tmp="${EVENTS_FILE}.tmp"
        tail -n "$MAX_EVENTS" "$EVENTS_FILE" > "$tmp"
        mv "$tmp" "$EVENTS_FILE"
    fi

    qlog_info "EVENT [${etype}] ${message}"
}

# Snapshot current state into prev_ev_* variables (called once after first parse)
snapshot_event_state() {
    prev_ev_network_type="$network_type"
    prev_ev_lte_band="$lte_band"
    prev_ev_lte_pci="$lte_pci"
    prev_ev_nr_band="$nr_band"
    prev_ev_nr_pci="$nr_pci"
    prev_ev_nr_state="$nr_state"
    prev_ev_modem_reachable="$modem_reachable"
    prev_ev_internet="$conn_internet_available"
    prev_ev_ca_active="$t2_ca_active"
    prev_ev_ca_count="$t2_ca_count"
    prev_ev_nr_ca_active="$t2_nr_ca_active"
    prev_ev_nr_ca_count="$t2_nr_ca_count"
    prev_ev_service_status="$service_status"
}

# Compare current state vs previous and emit events for any changes
detect_events() {
    # First cycle: populate previous state, don't generate events
    if [ "$events_initialized" = "false" ]; then
        snapshot_event_state
        events_initialized=true
        qlog_debug "Event detection initialized"
        return
    fi

    # --- Modem reachability ---
    if [ "$modem_reachable" != "$prev_ev_modem_reachable" ]; then
        if [ "$modem_reachable" = "true" ]; then
            append_event "signal_restored" "Modem signal restored" "info"
        else
            append_event "signal_lost" "Modem became unreachable" "warning"
            # Don't generate band/PCI events when modem goes away
            snapshot_event_state
            return
        fi
    fi

    # Skip detailed checks if modem is unreachable
    if [ "$modem_reachable" != "true" ]; then
        snapshot_event_state
        return
    fi

    # --- Network mode change ---
    if [ -n "$network_type" ] && [ -n "$prev_ev_network_type" ] && \
       [ "$network_type" != "$prev_ev_network_type" ]; then
        # Determine if upgrade or downgrade: 5G-SA > 5G-NSA > LTE
        local mode_severity="info"
        case "$prev_ev_network_type-$network_type" in
            5G-SA-5G-NSA|5G-SA-LTE|5G-NSA-LTE) mode_severity="warning" ;;
        esac
        append_event "network_mode" "Network mode changed from $prev_ev_network_type to $network_type" "$mode_severity"
    fi

    # --- LTE band change ---
    if [ -n "$lte_band" ] && [ -n "$prev_ev_lte_band" ] && \
       [ "$lte_band" != "$prev_ev_lte_band" ]; then
        append_event "band_change" "LTE band changed from $prev_ev_lte_band to $lte_band" "info"
    fi

    # --- LTE PCI change (cell handoff) ---
    if [ -n "$lte_pci" ] && [ -n "$prev_ev_lte_pci" ] && \
       [ "$lte_pci" != "$prev_ev_lte_pci" ]; then
        append_event "pci_change" "LTE cell handoff (PCI: $prev_ev_lte_pci -> $lte_pci)" "info"
    fi

    # --- NR state change (5G anchor gained/lost) ---
    if [ -n "$nr_state" ] && [ -n "$prev_ev_nr_state" ] && \
       [ "$nr_state" != "$prev_ev_nr_state" ]; then
        if [ "$nr_state" = "connected" ] && [ "$prev_ev_nr_state" != "connected" ]; then
            append_event "nr_anchor" "5G NR anchor acquired ($nr_band)" "info"
        elif [ "$nr_state" != "connected" ] && [ "$prev_ev_nr_state" = "connected" ]; then
            append_event "nr_anchor" "5G NR anchor lost" "warning"
        fi
    fi

    # --- NR band change ---
    if [ "$nr_state" = "connected" ] && \
       [ -n "$nr_band" ] && [ -n "$prev_ev_nr_band" ] && \
       [ "$nr_band" != "$prev_ev_nr_band" ]; then
        append_event "band_change" "NR band changed from $prev_ev_nr_band to $nr_band" "info"
    fi

    # --- NR PCI change ---
    if [ "$nr_state" = "connected" ] && \
       [ -n "$nr_pci" ] && [ -n "$prev_ev_nr_pci" ] && \
       [ "$nr_pci" != "$prev_ev_nr_pci" ]; then
        append_event "pci_change" "NR cell handoff (PCI: $prev_ev_nr_pci -> $nr_pci)" "info"
    fi

    # --- LTE CA changes ---
    if [ "$t2_ca_active" != "$prev_ev_ca_active" ]; then
        if [ "$t2_ca_active" = "true" ]; then
            append_event "ca_change" "LTE Carrier Aggregation activated ($((t2_ca_count + 1)) carriers)" "info"
        elif [ "$prev_ev_ca_active" = "true" ]; then
            append_event "ca_change" "LTE Carrier Aggregation deactivated" "warning"
        fi
    elif [ "$t2_ca_active" = "true" ] && [ "$t2_ca_count" != "$prev_ev_ca_count" ]; then
        local prev_total=$((prev_ev_ca_count + 1))
        local new_total=$((t2_ca_count + 1))
        local ca_sev="info"
        [ "$new_total" -lt "$prev_total" ] && ca_sev="warning"
        append_event "ca_change" "LTE carriers changed from $prev_total to $new_total" "$ca_sev"
    fi

    # --- NR CA changes ---
    if [ "$t2_nr_ca_active" != "$prev_ev_nr_ca_active" ]; then
        if [ "$t2_nr_ca_active" = "true" ]; then
            append_event "ca_change" "NR Carrier Aggregation activated ($((t2_nr_ca_count + 1)) NR carriers)" "info"
        elif [ "$prev_ev_nr_ca_active" = "true" ]; then
            append_event "ca_change" "NR Carrier Aggregation deactivated" "warning"
        fi
    elif [ "$t2_nr_ca_active" = "true" ] && [ "$t2_nr_ca_count" != "$prev_ev_nr_ca_count" ]; then
        local prev_total=$((prev_ev_nr_ca_count + 1))
        local new_total=$((t2_nr_ca_count + 1))
        local nr_ca_sev="info"
        [ "$new_total" -lt "$prev_total" ] && nr_ca_sev="warning"
        append_event "ca_change" "NR carriers changed from $prev_total to $new_total" "$nr_ca_sev"
    fi

    # --- Internet connectivity ---
    if [ "$conn_internet_available" != "$prev_ev_internet" ]; then
        if [ "$conn_internet_available" = "true" ] && [ "$prev_ev_internet" = "false" ]; then
            append_event "internet_restored" "Internet connectivity restored" "info"
        elif [ "$conn_internet_available" = "false" ] && [ "$prev_ev_internet" = "true" ]; then
            append_event "internet_lost" "Internet connectivity lost" "warning"
        fi
    fi

    # Update snapshot
    snapshot_event_state
}
