#!/bin/sh
# =============================================================================
# events.sh — Network Event Detection for QManager
# =============================================================================
# Sourced by qmanager_poller. Detects changes in network state and appends
# events to the NDJSON events file for the Recent Activities component.
#
# Dependencies: qlog_* functions, global state variables from poller
# Install location: /usr/lib/qmanager/events.sh
#
# Global variables used (defined in poller):
#   Read:  network_type, lte_band, lte_pci, nr_band, nr_pci, nr_state,
#          modem_reachable, conn_internet_available, conn_latency,
#          conn_avg_latency, conn_packet_loss, t2_ca_active, t2_ca_count,
#          t2_nr_ca_active, t2_nr_ca_count, t2_carrier_components,
#          service_status
#   Write: prev_ev_*, ev_high_lat_streak, ev_high_loss_streak,
#          ev_lat_alerted, ev_loss_alerted, events_initialized
# =============================================================================

[ -n "$_EVENTS_LOADED" ] && return 0
_EVENTS_LOADED=1

PCI_STATE_FILE="/tmp/qmanager_pci_state.json"

# Append a single event to the events file (NDJSON — one JSON per line)
# Note: All message content is generated by us (band names, PCI numbers, etc.)
# so no user-input escaping is needed.
append_event() {
    local etype="$1" message="$2" severity="${3:-info}"
    local ts
    ts=$(date +%s)

    jq -n -c \
        --argjson ts "$ts" \
        --arg type "$etype" \
        --arg message "$message" \
        --arg severity "$severity" \
        '{timestamp: $ts, type: $type, message: $message, severity: $severity}' >> "$EVENTS_FILE"

    # Trim to max entries
    local count
    count=$(wc -l < "$EVENTS_FILE" 2>/dev/null || echo 0)
    if [ "$count" -gt "$MAX_EVENTS" ]; then
        local tmp="${EVENTS_FILE}.tmp"
        if tail -n "$MAX_EVENTS" "$EVENTS_FILE" > "$tmp" 2>/dev/null; then
            mv "$tmp" "$EVENTS_FILE" 2>/dev/null || rm -f "$tmp"
        else
            rm -f "$tmp"
        fi
    fi

    qlog_info "EVENT [${etype}] ${message}"
}

# Snapshot current state into prev_ev_* variables (called once after first parse)
snapshot_event_state() {
    prev_ev_network_type="$network_type"
    prev_ev_lte_band="$lte_band"
    prev_ev_lte_pci="$lte_pci"
    prev_ev_nr_band="$nr_band"
    prev_ev_nr_pci="$nr_pci"
    prev_ev_nr_state="$nr_state"
    prev_ev_modem_reachable="$modem_reachable"
    prev_ev_internet="$conn_internet_available"
    prev_ev_ca_active="$t2_ca_active"
    prev_ev_ca_count="$t2_ca_count"
    prev_ev_nr_ca_active="$t2_nr_ca_active"
    prev_ev_nr_ca_count="$t2_nr_ca_count"
    prev_ev_service_status="$service_status"
    prev_ev_cfun="$t1_cfun"
    prev_ev_carrier_components="$t2_carrier_components"
}

# ---------------------------------------------------------------------------
# SCC PCI change detection via temp JSON
# ---------------------------------------------------------------------------
# Compares current t2_carrier_components against saved state in PCI_STATE_FILE.
# Only called when t2_carrier_components string has changed (Tier 2 refresh).
detect_scc_pci_changes() {
    local prev_sccs curr_sccs

    # Build current SCC list: tech+band+pci for SCC entries only
    curr_sccs=$(printf '%s' "$t2_carrier_components" | \
        jq -c '[.[] | select(.type == "SCC") | {tech: .technology, band: .band, pci: .pci}]' 2>/dev/null)
    [ -z "$curr_sccs" ] && curr_sccs="[]"

    # Read previous state from file
    if [ -f "$PCI_STATE_FILE" ]; then
        prev_sccs=$(cat "$PCI_STATE_FILE" 2>/dev/null)
        [ -z "$prev_sccs" ] && prev_sccs="[]"
    else
        # First run — save current state, no events
        printf '%s\n' "$curr_sccs" > "$PCI_STATE_FILE"
        return
    fi

    # Compare each current SCC against previous (matched by tech+band)
    local i=0
    local curr_count
    curr_count=$(printf '%s' "$curr_sccs" | jq 'length')

    while [ "$i" -lt "$curr_count" ]; do
        local c_tech c_band c_pci p_pci
        c_tech=$(printf '%s' "$curr_sccs" | jq -r ".[$i].tech")
        c_band=$(printf '%s' "$curr_sccs" | jq -r ".[$i].band")
        c_pci=$(printf '%s' "$curr_sccs" | jq -r ".[$i].pci")

        # Find matching entry in previous state
        p_pci=$(printf '%s' "$prev_sccs" | \
            jq -r --arg t "$c_tech" --arg b "$c_band" \
            '[.[] | select(.tech == $t and .band == $b)] | .[0].pci | if . == null then empty else tostring end')

        # If previous PCI exists and differs, emit event
        if [ -n "$p_pci" ] && [ "$p_pci" != "null" ] && [ "$p_pci" != "$c_pci" ]; then
            append_event "scc_pci_change" \
                "$c_tech $c_band SCC cell handoff (PCI: $p_pci -> $c_pci)" "info"
        fi

        i=$((i + 1))
    done

    # Save current state for next comparison
    printf '%s\n' "$curr_sccs" > "$PCI_STATE_FILE"
}

# ---------------------------------------------------------------------------
# Data connection quality checks (debounced — 3 consecutive readings)
# ---------------------------------------------------------------------------
detect_data_connection_events() {
    # Suppress internet events during active watchcat recovery.
    # Prevents spurious internet_lost/restored events from recovery actions
    # (Tier 1 ifup/ifdown, Tier 2 CFUN toggle, Tier 3 SIM switch).
    # Also prevents email alerts from firing during recovery.
    if [ "$conn_during_recovery" = "true" ]; then
        prev_ev_internet="$conn_internet_available"   # keep state in sync
        return
    fi

    # --- Internet connectivity ---
    if [ "$conn_internet_available" != "$prev_ev_internet" ]; then
        if [ "$conn_internet_available" = "true" ] && [ "$prev_ev_internet" = "false" ]; then
            append_event "internet_restored" "Internet connectivity restored" "info"
        elif [ "$conn_internet_available" = "false" ] && [ "$prev_ev_internet" = "true" ]; then
            append_event "internet_lost" "Internet connectivity lost" "warning"
        fi
    fi

    # --- High latency detection (threshold: 90ms, debounce: 3 readings) ---
    # Skip when ping daemon is stale (conn_latency="null") — don't touch streaks
    if [ "$conn_latency" != "null" ] && [ -n "$conn_latency" ]; then
        # Use awk for decimal comparison (POSIX shell has no float math)
        if echo "$conn_latency" | awk '{exit !($1 > 90)}'; then
            ev_high_lat_streak=$((ev_high_lat_streak + 1))
            if [ "$ev_high_lat_streak" -ge 3 ] && [ "$ev_lat_alerted" = "false" ]; then
                append_event "high_latency" \
                    "High latency detected (${conn_latency}ms, avg ${conn_avg_latency}ms)" "warning"
                ev_lat_alerted=true
            fi
        else
            # Latency below threshold — recover if previously alerted
            if [ "$ev_lat_alerted" = "true" ]; then
                append_event "latency_recovered" \
                    "Latency recovered (${conn_latency}ms)" "info"
            fi
            ev_high_lat_streak=0
            ev_lat_alerted=false
        fi
    fi

    # --- High packet loss detection (threshold: 20%, debounce: 3 readings) ---
    if [ "$conn_packet_loss" != "null" ] && [ -n "$conn_packet_loss" ]; then
        if [ "$conn_packet_loss" -ge 20 ] 2>/dev/null; then
            ev_high_loss_streak=$((ev_high_loss_streak + 1))
            if [ "$ev_high_loss_streak" -ge 3 ] && [ "$ev_loss_alerted" = "false" ]; then
                append_event "high_packet_loss" \
                    "High packet loss detected (${conn_packet_loss}%)" "warning"
                ev_loss_alerted=true
            fi
        else
            # Packet loss below threshold — recover if previously alerted
            if [ "$ev_loss_alerted" = "true" ]; then
                append_event "packet_loss_recovered" \
                    "Packet loss recovered (${conn_packet_loss}%)" "info"
            fi
            ev_high_loss_streak=0
            ev_loss_alerted=false
        fi
    fi
}

# Compare current state vs previous and emit events for any changes
detect_events() {
    # Suppress all events during scheduled low power mode
    if [ -f "/tmp/qmanager_low_power_active" ]; then
        snapshot_event_state
        return
    fi

    # First cycle: populate previous state, don't generate events
    if [ "$events_initialized" = "false" ]; then
        snapshot_event_state
        # Initialize PCI state file with current SCCs
        if [ -n "$t2_carrier_components" ] && [ "$t2_carrier_components" != "[]" ]; then
            printf '%s' "$t2_carrier_components" | \
                jq -c '[.[] | select(.type == "SCC") | {tech: .technology, band: .band, pci: .pci}]' \
                > "$PCI_STATE_FILE" 2>/dev/null
        fi
        events_initialized=true
        qlog_debug "Event detection initialized"
        return
    fi

    # =====================================================================
    # Section 1: Network Mode events
    # =====================================================================

    # --- Modem reachability ---
    if [ "$modem_reachable" != "$prev_ev_modem_reachable" ]; then
        if [ "$modem_reachable" = "true" ]; then
            append_event "signal_restored" "Modem signal restored" "info"
        else
            append_event "signal_lost" "Modem became unreachable" "warning"
            # Don't generate band/PCI events when modem goes away
            snapshot_event_state
            return
        fi
    fi

    # Skip detailed checks if modem is unreachable
    if [ "$modem_reachable" != "true" ]; then
        snapshot_event_state
        return
    fi

    # --- Airplane mode (CFUN transition) ---
    if [ "$t1_cfun" != "$prev_ev_cfun" ]; then
        if [ "$prev_ev_cfun" = "1" ] && { [ "$t1_cfun" = "0" ] || [ "$t1_cfun" = "4" ]; }; then
            append_event "airplane_mode" "Airplane mode enabled (CFUN=$t1_cfun)" "warning"
        elif { [ "$prev_ev_cfun" = "0" ] || [ "$prev_ev_cfun" = "4" ]; } && [ "$t1_cfun" = "1" ]; then
            append_event "airplane_mode" "Airplane mode disabled" "info"
        fi
    fi

    # --- Network mode change ---
    if [ -n "$network_type" ] && [ -n "$prev_ev_network_type" ] && \
       [ "$network_type" != "$prev_ev_network_type" ]; then
        # Determine if upgrade or downgrade: 5G-SA > 5G-NSA > LTE
        local mode_severity="info"
        case "$prev_ev_network_type-$network_type" in
            5G-SA-5G-NSA|5G-SA-LTE|5G-NSA-LTE) mode_severity="warning" ;;
        esac
        append_event "network_mode" "Network mode changed from $prev_ev_network_type to $network_type" "$mode_severity"
    fi

    # =====================================================================
    # Section 2: Band Changes events
    # =====================================================================

    # --- LTE band change ---
    if [ -n "$lte_band" ] && [ -n "$prev_ev_lte_band" ] && \
       [ "$lte_band" != "$prev_ev_lte_band" ]; then
        append_event "band_change" "LTE band changed from $prev_ev_lte_band to $lte_band" "info"
    fi

    # --- LTE PCI change (PCC cell handoff) ---
    if [ -n "$lte_pci" ] && [ -n "$prev_ev_lte_pci" ] && \
       [ "$lte_pci" != "$prev_ev_lte_pci" ]; then
        append_event "pci_change" "LTE PCC cell handoff (PCI: $prev_ev_lte_pci -> $lte_pci)" "info"
    fi

    # --- NR state change (5G anchor gained/lost) ---
    if [ -n "$nr_state" ] && [ -n "$prev_ev_nr_state" ] && \
       [ "$nr_state" != "$prev_ev_nr_state" ]; then
        if [ "$nr_state" = "connected" ] && [ "$prev_ev_nr_state" != "connected" ]; then
            append_event "nr_anchor" "5G NR anchor acquired ($nr_band)" "info"
        elif [ "$nr_state" != "connected" ] && [ "$prev_ev_nr_state" = "connected" ]; then
            append_event "nr_anchor" "5G NR anchor lost" "warning"
        fi
    fi

    # --- NR band change ---
    if [ "$nr_state" = "connected" ] && \
       [ -n "$nr_band" ] && [ -n "$prev_ev_nr_band" ] && \
       [ "$nr_band" != "$prev_ev_nr_band" ]; then
        append_event "band_change" "NR band changed from $prev_ev_nr_band to $nr_band" "info"
    fi

    # --- NR PCI change (PCC) ---
    if [ "$nr_state" = "connected" ] && \
       [ -n "$nr_pci" ] && [ -n "$prev_ev_nr_pci" ] && \
       [ "$nr_pci" != "$prev_ev_nr_pci" ]; then
        append_event "pci_change" "NR PCC cell handoff (PCI: $prev_ev_nr_pci -> $nr_pci)" "info"
    fi

    # --- LTE CA changes ---
    if [ "$t2_ca_active" != "$prev_ev_ca_active" ]; then
        if [ "$t2_ca_active" = "true" ]; then
            append_event "ca_change" "LTE Carrier Aggregation activated ($((t2_ca_count + 1)) carriers)" "info"
        elif [ "$prev_ev_ca_active" = "true" ]; then
            append_event "ca_change" "LTE Carrier Aggregation deactivated" "warning"
        fi
    elif [ "$t2_ca_active" = "true" ] && [ "$t2_ca_count" != "$prev_ev_ca_count" ]; then
        local prev_total=$((prev_ev_ca_count + 1))
        local new_total=$((t2_ca_count + 1))
        local ca_sev="info"
        [ "$new_total" -lt "$prev_total" ] && ca_sev="warning"
        append_event "ca_change" "LTE carriers changed from $prev_total to $new_total" "$ca_sev"
    fi

    # --- NR CA changes ---
    if [ "$t2_nr_ca_active" != "$prev_ev_nr_ca_active" ]; then
        if [ "$t2_nr_ca_active" = "true" ]; then
            append_event "ca_change" "NR Carrier Aggregation activated ($((t2_nr_ca_count + 1)) NR carriers)" "info"
        elif [ "$prev_ev_nr_ca_active" = "true" ]; then
            append_event "ca_change" "NR Carrier Aggregation deactivated" "warning"
        fi
    elif [ "$t2_nr_ca_active" = "true" ] && [ "$t2_nr_ca_count" != "$prev_ev_nr_ca_count" ]; then
        local prev_total=$((prev_ev_nr_ca_count + 1))
        local new_total=$((t2_nr_ca_count + 1))
        local nr_ca_sev="info"
        [ "$new_total" -lt "$prev_total" ] && nr_ca_sev="warning"
        append_event "ca_change" "NR carriers changed from $prev_total to $new_total" "$nr_ca_sev"
    fi

    # --- SCC PCI changes (detected on Tier 2 refresh) ---
    if [ "$t2_carrier_components" != "$prev_ev_carrier_components" ]; then
        detect_scc_pci_changes
    fi

    # =====================================================================
    # Section 3: Data Connection events
    # =====================================================================
    detect_data_connection_events

    # Update snapshot
    snapshot_event_state
}
